### ISSUE TITLE
REVIEW Week9

### ISSUE THREAD

**Issue by ShinRuHung** [SOA-nuts/PortfolioAdvisor#21]
please see #20

**Comment by tienyulin** [comment]
I didn't see the `Procfile` in your repository for Heroku, seems like you haven't published your app to Heroku?
@ShinRuHung

**Comment by ChungYiTsai** [comment]
Hi @tienyulin  , 
Since our DB can't generate table correctly last week, we didn't push it to herouku.
After ask you question about this problem on Monday, we have solved this problem at the develop branch.
Shall we pushed it back to master now, or you can just see our  [develop branch](https://github.com/SOA-nuts/PortfolioAdvisor/tree/develop)?

Also , thanks for your help!!!

**Comment by tienyulin** [comment]
Got it, I saw it on the develop branch. No need to merge back to master now. Keep working on this week's assignment and good luck!
